# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack'
        inputs:
          command: pack
          packagesToPack: 'src/*.csproj'
          versioningScheme: byEnvVar
          versionEnvVar: nugetPackVersion
      #  condition: and(Succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- stage: Test
  jobs:
  - job: Test
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'VsTest - testAssemblies'
        inputs:
          command: 'test'
          projects: '**/Codemancer.Extensions.Wcf.Tests.csproj'
          testRunTitle: 'Testing'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet push'
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: 'NuGet service connection'
        enabled: false
      #  condition: and(Succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

      - task: NuGetCommand@2
        displayName: 'NuGet push'
        inputs:
          command: push
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: external
          publishFeedCredentials: 'NuGet service connection'
      #  condition: and(Succeeded(), ne(variables['Build.Reason'], 'PullRequest'))