# Variable 'nugetPackageVersion' was defined in the Variables tab

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

trigger:
 branches:
    include:
      -  features/*

variables:
  version: 0.0
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    semVer: $(version).0
  ${{ else }}:
    semVer: $(version).0-beta.$(Build.BuildNumber)
    assemblyVersion: "$(version).0.$(Build.BuildNumber)"

jobs:
- job: Job_1
  displayName: Create Package

  pool:
    vmImage: windows-latest
    name: $(Rev:r)

  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      arguments: --configuration Release -property:Version=$(assemblyVersion)
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/Codemancer.Extensions.Wcf.Tests.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      searchPatternPack: src/*.csproj
      versioningScheme: byEnvVar
      versionEnvVar: semVer
  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
